const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
const TOGGLE_CHANGE_STATUS = 'TOGGLE_CHANGE_STATUS';
const INIT_TODOS = 'INIT_TODOS';

const INIT_TAGS = 'INIT_TAGS';
const ADD_TAG = 'ADD_TAG';

export {
  ADD_TODO_ITEM,
  UPDATE_TODO_ITEM,
  REMOVE_TODO_ITEM,
  TOGGLE_CHANGE_STATUS,
  INIT_TODOS,
  INIT_TAGS,
  ADD_TAG,
};
