const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
const TOGGLE_CHANGE_STATUS = 'TOGGLE_CHANGE_STATUS';

export { ADD_TODO_ITEM, REMOVE_TODO_ITEM, TOGGLE_CHANGE_STATUS };
