const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
const TOGGLE_CHANGE_STATUS = 'TOGGLE_CHANGE_STATUS';
const INIT_TODOS = 'INIT_TODOS';

export {
  ADD_TODO_ITEM,
  UPDATE_TODO_ITEM,
  REMOVE_TODO_ITEM,
  TOGGLE_CHANGE_STATUS,
  INIT_TODOS,
};
